### ISSUE TITLE
Create Landing Page with Hero Image/Content

### ISSUE THREAD

**Issue by briancbarrow** [FreeCodeCamp-SLC/utahjs-gatsby#1]
Set up the landing page to look like it currently does on utahjs.com

**Comment by briancbarrow** [comment]
![Uploading Screen Shot 2020-09-29 at 6.16.47 PM.png…]()

**Comment by briancbarrow** [comment]
![Screen Shot 2020-09-29 at 6 16 47 PM](https://user-images.githubusercontent.com/13695093/94629476-28e38180-0280-11eb-9872-d59d16f6d27b.png)

**Comment by briancbarrow** [comment]
Instead of having the image as a background, lets use a placeholder from https://bgjar.com/

**Comment by AlexanderPuhl** [comment]
Moved this back into the "To Do" list. The old UtahJS website hero image stretched across the screen while the new landing page hero section is locked into a certain width with the rest of the content below. Might want to adjust it so it's more in line with the old utahjs website, we can ask Brian about this. Also the image is different, do we want to use the old image?
