### ISSUE TITLE
Make the year button on the past-speakers page dynamic.

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/utahjs-gatsby#122]
Remove the hardcoding of the years for the "View 2018 Speakers" button and figure out how to get the button to be more dynamic and get it's information from Sanity. Maybe have pagination like what Justin was talking about.

**Comment by AlexanderPuhl** [comment]
We'll wait on this until we have at least 3 years in sessionize.

**Comment by kensnyder** [comment]
Addressed by #147
