### ISSUE TITLE
Mobile Nav dropdown is behind the schedule.

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/utahjs-gatsby#156]
![image](https://user-images.githubusercontent.com/22256166/181659823-7d46c472-e86d-420a-a9c1-0248b3ecc35a.png)

Need a z-index so the schedule isn't in front of the mobile nav menu.

**Comment by jgbowser** [comment]
@AlexanderPuhl I was going to get started on this ticket, but it looks like it isn't actually an issue with this year's schedule. I think there was maybe some custom styling on the previous schedule which caused this. Looks like this issue can just be closed out.
![Screen Shot 2022-08-01 at 4 22 56 PM](https://user-images.githubusercontent.com/66637570/182255823-9329d288-4b18-46a2-9da7-47b5e6b4e196.png)
