### ISSUE TITLE
Finish Past Speakers Page

### ISSUE THREAD

**Issue by mikelnorth** [FreeCodeCamp-SLC/utahjs-gatsby#29]
The speakers page has been templated out and needs to be finished by filling in the rest of the data and finishing the styling

**Comment by AlexanderPuhl** [comment]
I've put this back into the "To Do" list. The link is trying to go to "past-speakers" when the page is called "speakers". One or the other needs to be updated so they're in sync.

**Comment by AlexanderPuhl** [comment]
Justin got the page working again, pushed it up and requested a pull request, I merged it into main. Keeping this issue open. Justin will work on getting past speaker data to show up like the old site.
