### ISSUE TITLE
Move Speakers Data To Sanity

### ISSUE THREAD

**Issue by mikelnorth** [FreeCodeCamp-SLC/utahjs-gatsby#35]
We want to move the speaker data found in data/speakers.js to sanity.io so that we can have site admins update the content as needed.

You will need to get the sanity.io api token from @mikelnorth to connect your sanity studio for development.

**Comment by mikelnorth** [comment]
This is dependent on the speaker's page being completed

**Comment by AlexanderPuhl** [comment]
I got this finished.
