### ISSUE TITLE
Sponsor Us Page

### ISSUE THREAD

**Issue by mikelnorth** [FreeCodeCamp-SLC/utahjs-gatsby#36]
We need to create this page
https://conf.utahjs.com/sponsor
![Screen Shot 2020-10-21 at 9 59 59 AM](https://user-images.githubusercontent.com/5479019/96746215-2f977d00-1384-11eb-8981-681b3cfd409f.png)

**Comment by AlexanderPuhl** [comment]
This has been finished, but it needs a navbar added which has already been created, just needs the component added, will create a new issue specifying so.
