### ISSUE TITLE
Create Code of Conduct Page

### ISSUE THREAD

**Issue by mikelnorth** [FreeCodeCamp-SLC/utahjs-gatsby#37]
We need to create this page
https://conf.utahjs.com/code-of-conduct
![Screen Shot 2020-10-21 at 10 01 40 AM](https://user-images.githubusercontent.com/5479019/96746453-6bcadd80-1384-11eb-834a-f33feeea2592.png)

**Comment by mikelnorth** [comment]
Close in error

**Comment by AlexanderPuhl** [comment]
This has essentially been finished.
