### ISSUE TITLE
Add Code of Conduct md 

### ISSUE THREAD

**Issue by mikelnorth** [FreeCodeCamp-SLC/utahjs-gatsby#38]
copy the less quick version code of conduct from 

Put this in a markdown file called codeOfConduct.md in the root of the projectct
https://conf.utahjs.com/code-of-conduct

**Comment by Loganras** [comment]
Do we want a header in the file as well?  Or just the paragraphs?

**Comment by Loganras** [comment]
@mikelnorth We should probably consider closing this issue in favor of issue #37 which already has a PR ready.

**Comment by AlexanderPuhl** [comment]
This has been finished.
