### ISSUE TITLE
Update landing page hero image

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/utahjs-gatsby#56]
![image](https://user-images.githubusercontent.com/22256166/100811164-355a9680-33f7-11eb-89ff-938f61263a34.png)

We need to use the arch.jpg image as the hero image on the landing page. It should also stretch across the screen instead of being constricted to 1240px. Use https://utahjs.com/ as an example, we're aiming to recreate the website exactly as it is before we think about making changes.

**Comment by jgbowser** [comment]
I had initially constricted it to 1240px because Brian wanted it to match the conference page hero image sizing. Not sure if that is still the case though, but that is why it is set up like it is as of now.
