### ISSUE TITLE
Create Nav Component

### ISSUE THREAD

**Issue by briancbarrow** [FreeCodeCamp-SLC/utahjs-gatsby#8]
We need a consistent nav across the site. see the nav section on conf.utahjs.com for reference

**Comment by mikelnorth** [comment]
This is to just create the Nav, not the pages it links to.

There are multiple links in the Nav that go outside of utahjs.com, we would want those links to be setup
![Screen Shot 2020-10-21 at 9 58 42 AM](https://user-images.githubusercontent.com/5479019/96746034-024acf00-1384-11eb-85b7-949673ae5e6d.png)

**Comment by AlexanderPuhl** [comment]
This has been finished.
