### ISSUE TITLE
Develop the code of conduct page to be mobile responsive. 

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/utahjs-gatsby#81]
Use the old UtahJS website as a guide on where to set breakpoints, but these are just guidelines we may have to adjust where the breakpoints are or even create new breakpoints. We want to be able to go down to a screen size of 320 pixels which is the size of an iPhone 5/SE. As you play around with shrinking the page size, pay attention to boxes or text breaking out of their containers. Make sure that we maintain a bit of padding on the edges of the screen at all times. Here is an image of the old site once it gets down to 320px wide which is the width of an iPhone 5/SE.

![image](https://user-images.githubusercontent.com/22256166/102320532-a8a4f200-3f39-11eb-9d74-9b57fbfffb30.png)

**Comment by jgbowser** [comment]
Looking at how it is displaying currently I am not seeing any issues. Were there any specific issues you noticed? Padding and font size all look great. This issue might be able to be closed without any changes.

**Comment by AlexanderPuhl** [comment]
Took another look at the COC page and confirmed what John said that it really is good to go and no work needs to be done.
