### ISSUE TITLE
Implement SEO for the conference page.

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/utahjs-gatsby#99]
We need to get this stuff to load into the header tag for the conference page.

![image](https://user-images.githubusercontent.com/22256166/104074040-6c795000-51cc-11eb-9d4c-547a04b25d72.png)

**Comment by stevenCsaunders** [comment]
The SEO code was already added to the page, so I added a Conference Page document to the SEO folder in Sanity.
